# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Mnn <- function(X, M) {
    .Call(`_MySpectralClustering_Mnn`, X, M)
}

GenerateG <- function(S) {
    .Call(`_MySpectralClustering_GenerateG`, S)
}

ModifyG <- function(G) {
    .Call(`_MySpectralClustering_ModifyG`, G)
}

GenerateD <- function(G) {
    .Call(`_MySpectralClustering_GenerateD`, G)
}

